language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy

env:
    global:
        - PYFLAKES_NODOCTEST=1
    matrix:
        - TWISTED=Twisted==15.5
        - TWISTED=Twisted==16.4
        - TWISTED=https://github.com/twisted/twisted/archive/trunk.zip

matrix:
    exclude:
        - python: 3.3
          env: TWISTED=Twisted==15.5
        - python: 3.5
          env: TWISTED=Twisted==15.5
        - python: 3.6
          env: TWISTED=Twisted==15.5

install:
    - pip install -q $TWISTED
    - pip install .[dev]

script:
    - pyflakes wokkel twisted
    - trial wokkel
