language: python

python:
    - 2.6
    - 2.7
    - pypy

env:
    - TWISTED=Twisted==12.3
    - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk
    - PYFLAKES_NODOCTEST=1

install:
    - pip install pyflakes --use-mirrors
    - pip install -q $TWISTED --use-mirrors
    - python setup.py install

script:
    - pyflakes wokkel twisted
    - trial wokkel
